### ISSUE TITLE
Support for spaces in path

### ISSUE THREAD

**Issue by henrik-brodtkorb** [hauntsaninja/atom-black#2]
Got this error message when attempting to run Black through atom-black. Not sure if I missed something on my end. 

![image](https://user-images.githubusercontent.com/41117355/44710733-b605ec00-aaa4-11e8-9b30-e7d01100c264.png)

However, black does run through command line: 
![image](https://user-images.githubusercontent.com/41117355/44710942-2f054380-aaa5-11e8-9467-3dacebf37e79.png)

*Please could you advise whether it is just me, and how I could overcome this issue?*

Thanks!

**Comment by hauntsaninja** [comment]
Hey, thank you for reporting this! I've pushed a fix, if you update your package (`apm upgrade atom-black`) this should be resolved.

**Comment by henrik-brodtkorb** [comment]
Hi, thanks for the quick turnaround time.
However, I am still getting error: 

![image](https://user-images.githubusercontent.com/41117355/44776121-3db82d00-ab6f-11e8-8311-54e542168a4d.png)

path: `G:\My Drive\3W - CORE\Team_folders\RAD\Scripts\Python\test.py`

**Comment by hauntsaninja** [comment]
Hmm. I suspect this might be a Windows issue, however, I don't have an easily available Windows computer at hand. Would you mind testing out a fix?
```
git clone https://github.com/hauntsaninja/atom-black.git
cd atom-black
git checkout windowspace
apm uninstall atom-black
apm link
```
And then either restarting Atom, or running `Window: Reload`

**Comment by henrik-brodtkorb** [comment]
Hi, I fixed the error. The issue was that Black didn't like `^` in the path string. 

Fixed it by adding quotes around the path (line 85):
```javascript
...
if (process.platform == "win32") {
    path = "\"" +  path + "\"";
} else { 
...
```
